-- =============================================================================
-- P&D Connect - DDL completo do banco (PostgreSQL)
--
-- Gerado a partir dos models do Django (backend/apps/*/models.py), estado atual
-- das migrations. Reproduz o schema inteiro num banco vazio:
--
--   createdb pdconnect
--   psql -d pdconnect -f querys.sql
--
-- Ordem do arquivo: 1) tabelas  2) indices  3) chaves estrangeiras/unique.
-- As FKs vem no fim de proposito - assim nenhuma tabela precisa existir antes
-- da outra e o arquivo roda de cima para baixo sem erro de dependencia.
--
-- Para o Django reconhecer um banco criado por aqui sem reaplicar migration:
--   python manage.py migrate --fake
-- =============================================================================

BEGIN;

-- ############################  1. TABELAS  ############################

-- ---------------------------------------------------------------------------
-- accounts - Contas e acesso
-- ---------------------------------------------------------------------------

CREATE TABLE "token_acesso" (
    "id_token" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "id_usuario" bigint NOT NULL,
    "token" varchar(255) NOT NULL UNIQUE,
    "finalidade" varchar(12) NOT NULL,
    "expira_em" timestamp with time zone NOT NULL,
    "usado_em" timestamp with time zone NULL,
    "criado_em" timestamp with time zone NOT NULL
);

CREATE TABLE "usuario" (
    "last_login" timestamp with time zone NULL,
    "is_superuser" boolean NOT NULL,
    "criado_em" timestamp with time zone NOT NULL,
    "atualizado_em" timestamp with time zone NOT NULL,
    "id_usuario" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "nome" varchar(160) NOT NULL,
    "email" varchar(254) NOT NULL UNIQUE,
    "senha" varchar(128) NOT NULL,
    "papel" varchar(20) NOT NULL,
    "situacao" varchar(10) NOT NULL,
    "id_organizacao" bigint NULL,
    "ultimo_acesso" timestamp with time zone NULL,
    "acesso_admin_django" boolean NOT NULL
);

CREATE TABLE "usuario_groups" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "usuario_id" bigint NOT NULL,
    "group_id" integer NOT NULL
);

CREATE TABLE "usuario_user_permissions" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "usuario_id" bigint NOT NULL,
    "permission_id" integer NOT NULL
);

-- ---------------------------------------------------------------------------
-- organizations - Organizacoes
-- ---------------------------------------------------------------------------

CREATE TABLE "organizacao" (
    "criado_em" timestamp with time zone NOT NULL,
    "atualizado_em" timestamp with time zone NOT NULL,
    "id_organizacao" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "tipo" varchar(12) NOT NULL,
    "nome" varchar(180) NOT NULL,
    "razao_social" varchar(200) NULL,
    "cnpj" varchar(14) NULL UNIQUE,
    "municipio" varchar(120) NULL,
    "uf" varchar(2) NULL,
    "ativo" boolean NOT NULL,
    CONSTRAINT "ck_organizacao_demandante_tem_cnpj" CHECK ((("cnpj" IS NOT NULL AND "tipo" = 'demandante') OR "tipo" = 'instituicao'))
);

-- ---------------------------------------------------------------------------
-- network - Rede interna
-- ---------------------------------------------------------------------------

CREATE TABLE "competencia" (
    "criado_em" timestamp with time zone NOT NULL,
    "atualizado_em" timestamp with time zone NOT NULL,
    "id_competencia" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "nome" varchar(160) NOT NULL,
    "tipo" varchar(16) NOT NULL,
    "canonica" boolean NOT NULL,
    "id_sinonimo_de" bigint NULL,
    "ativo" boolean NOT NULL,
    CONSTRAINT "uq_competencia_nome_tipo" UNIQUE ("nome", "tipo")
);

CREATE TABLE "formacao" (
    "criado_em" timestamp with time zone NOT NULL,
    "atualizado_em" timestamp with time zone NOT NULL,
    "id_formacao" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "id_membro" bigint NOT NULL,
    "curso" varchar(180) NOT NULL,
    "instituicao" varchar(180) NOT NULL,
    "id_titulacao" bigint NULL,
    "ano_conclusao" smallint NULL CHECK ("ano_conclusao" >= 0)
);

CREATE TABLE "membro_competencia" (
    "id_membro_competencia" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "id_membro" bigint NOT NULL,
    "id_competencia" bigint NOT NULL,
    "nivel" smallint NULL CHECK ("nivel" >= 0),
    "declarado_por" varchar(12) NOT NULL,
    "criado_em" timestamp with time zone NOT NULL,
    CONSTRAINT "uq_membro_competencia" UNIQUE ("id_membro", "id_competencia")
);

CREATE TABLE "membro_rede" (
    "criado_em" timestamp with time zone NOT NULL,
    "atualizado_em" timestamp with time zone NOT NULL,
    "id_membro" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "id_usuario" bigint NULL UNIQUE,
    "nome" varchar(160) NOT NULL,
    "email" varchar(254) NOT NULL UNIQUE,
    "papel_rede" varchar(16) NOT NULL,
    "id_titulacao" bigint NULL,
    "id_organizacao" bigint NULL,
    "disponibilidade" varchar(14) NOT NULL,
    "experiencia" text NOT NULL,
    "situacao" varchar(12) NOT NULL,
    "cadastrado_por" bigint NULL
);

CREATE TABLE "titulacao" (
    "id_titulacao" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "codigo" varchar(40) NOT NULL UNIQUE,
    "rotulo" varchar(80) NOT NULL,
    "nivel" smallint NOT NULL CHECK ("nivel" >= 0)
);

-- ---------------------------------------------------------------------------
-- platform_settings - Configuracoes da plataforma
-- ---------------------------------------------------------------------------

CREATE TABLE "configuracao_plataforma" (
    "id_configuracao" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "secao" varchar(40) NOT NULL UNIQUE,
    "payload" jsonb NOT NULL,
    "revisao" integer NOT NULL CHECK ("revisao" >= 0),
    "atualizado_por" bigint NULL,
    "atualizado_em" timestamp with time zone NOT NULL
);

CREATE TABLE "contato_suporte" (
    "id_contato" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "nome" varchar(160) NOT NULL,
    "papel" varchar(120) NOT NULL,
    "email" varchar(254) NOT NULL,
    "telefone" varchar(40) NULL,
    "ordem" smallint NOT NULL CHECK ("ordem" >= 0),
    "ativo" boolean NOT NULL
);

-- ---------------------------------------------------------------------------
-- opportunities - Oportunidades
-- ---------------------------------------------------------------------------

CREATE TABLE "anexo_oportunidade" (
    "id_anexo" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "id_oportunidade" bigint NOT NULL,
    "arquivo" varchar(100) NOT NULL,
    "nome_original" varchar(255) NOT NULL,
    "mime" varchar(120) NOT NULL,
    "tamanho_bytes" bigint NOT NULL,
    "enviado_por" bigint NULL,
    "criado_em" timestamp with time zone NOT NULL
);

CREATE TABLE "oportunidade" (
    "id_oportunidade" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "codigo" varchar(14) NOT NULL UNIQUE,
    "titulo" varchar(200) NOT NULL,
    "origem" varchar(8) NOT NULL,
    "resumo" text NOT NULL,
    "contexto" text NOT NULL,
    "id_demandante" bigint NULL,
    "id_criado_por" bigint NULL,
    "id_responsavel" bigint NULL,
    "situacao" varchar(20) NOT NULL,
    "criada_em" timestamp with time zone NOT NULL,
    "atualizada_em" timestamp with time zone NOT NULL,
    CONSTRAINT "ck_oportunidade_origem_demandante" CHECK ((("id_demandante" IS NULL AND "origem" = 'interna') OR ("id_demandante" IS NOT NULL AND "origem" = 'externo')))
);

CREATE TABLE "sequencia_codigo" (
    "id_sequencia" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "ano" smallint NOT NULL UNIQUE CHECK ("ano" >= 0),
    "ultimo_numero" integer NOT NULL CHECK ("ultimo_numero" >= 0)
);

-- ---------------------------------------------------------------------------
-- ai - Execucoes de IA
-- ---------------------------------------------------------------------------

CREATE TABLE "execucao_ia" (
    "id_execucao_ia" uuid NOT NULL PRIMARY KEY,
    "tipo" varchar(16) NOT NULL,
    "provedor" varchar(40) NOT NULL,
    "modelo" varchar(80) NOT NULL,
    "versao_prompt" varchar(40) NOT NULL,
    "tokens_entrada" integer NULL,
    "tokens_saida" integer NULL,
    "custo_estimado" numeric(10, 6) NULL,
    "latencia_ms" integer NULL,
    "status" varchar(12) NOT NULL,
    "fallback_usado" boolean NOT NULL,
    "erro" text NOT NULL,
    "correlation_id" uuid NOT NULL,
    "executado_por" varchar(160) NOT NULL,
    "criado_em" timestamp with time zone NOT NULL,
    "concluido_em" timestamp with time zone NULL
);

-- ---------------------------------------------------------------------------
-- copilot - Copiloto de estruturacao
-- ---------------------------------------------------------------------------

CREATE TABLE "lacuna" (
    "id_lacuna" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "id_oportunidade" bigint NOT NULL,
    "tipo" varchar(12) NOT NULL,
    "descricao" text NOT NULL,
    "severidade" varchar(6) NULL,
    "id_competencia_necessaria" bigint NULL,
    "id_pre_analise" uuid NULL,
    "resolvida" boolean NOT NULL,
    "resolvida_em" timestamp with time zone NULL,
    "id_execucao_ia" uuid NULL,
    "criado_em" timestamp with time zone NOT NULL
);

CREATE TABLE "mensagem_copiloto" (
    "id_mensagem" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "id_sessao" uuid NOT NULL,
    "autor" varchar(10) NOT NULL,
    "conteudo" text NOT NULL,
    "ordem" integer NOT NULL CHECK ("ordem" >= 0),
    "id_execucao_ia" uuid NULL,
    "criado_em" timestamp with time zone NOT NULL,
    CONSTRAINT "uq_mensagem_sessao_ordem" UNIQUE ("id_sessao", "ordem")
);

CREATE TABLE "proposta_estruturada" (
    "criado_em" timestamp with time zone NOT NULL,
    "atualizado_em" timestamp with time zone NOT NULL,
    "id_proposta" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "id_oportunidade" bigint NOT NULL UNIQUE,
    "problema_pesquisa" text NOT NULL,
    "hipotese" text NULL,
    "objetivo_geral" text NOT NULL,
    "objetivos_especificos" jsonb NOT NULL,
    "metodologia" text NOT NULL,
    "resultados_esperados" text NOT NULL,
    "caracterizacao_inovacao" text NOT NULL,
    "infraestrutura_recursos" text NOT NULL,
    "versao" integer NOT NULL CHECK ("versao" >= 0),
    "revisada_por_humano" boolean NOT NULL,
    "id_revisor" bigint NULL,
    "id_execucao_ia" uuid NULL
);

CREATE TABLE "sessao_copiloto" (
    "id_sessao" uuid NOT NULL PRIMARY KEY,
    "id_oportunidade" bigint NOT NULL,
    "iniciada_por" bigint NULL,
    "estado" varchar(12) NOT NULL,
    "criado_em" timestamp with time zone NOT NULL,
    "encerrado_em" timestamp with time zone NULL
);

-- ---------------------------------------------------------------------------
-- competencies - Competencias necessarias
-- ---------------------------------------------------------------------------

CREATE TABLE "competencia_necessaria" (
    "id_competencia_necessaria" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "id_oportunidade" bigint NOT NULL,
    "id_competencia" bigint NULL,
    "descricao" varchar(200) NOT NULL,
    "essencial" boolean NOT NULL,
    "derivada_de" varchar(10) NOT NULL,
    "id_execucao_ia" uuid NULL,
    "criado_em" timestamp with time zone NOT NULL,
    "atualizado_em" timestamp with time zone NOT NULL,
    CONSTRAINT "uq_competencia_necessaria_oport_desc" UNIQUE ("id_oportunidade", "descricao")
);

-- ---------------------------------------------------------------------------
-- matching - Matching e equipe potencial
-- ---------------------------------------------------------------------------

CREATE TABLE "equipe_potencial" (
    "id_equipe_potencial" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "id_oportunidade" bigint NOT NULL,
    "id_membro" bigint NOT NULL,
    "id_execucao" uuid NULL,
    "papel_sugerido" varchar(16) NOT NULL,
    "score_match" numeric(5, 4) NULL,
    "match_reasons" jsonb NOT NULL,
    "score_features" jsonb NOT NULL,
    "origem" varchar(8) NOT NULL,
    "validada" boolean NOT NULL,
    "ajustado_por" bigint NULL,
    "criado_em" timestamp with time zone NOT NULL,
    "atualizado_em" timestamp with time zone NOT NULL,
    CONSTRAINT "uq_equipe_oportunidade_membro" UNIQUE ("id_oportunidade", "id_membro")
);

CREATE TABLE "execucao_matching" (
    "id_execucao" uuid NOT NULL PRIMARY KEY,
    "id_oportunidade" bigint NOT NULL,
    "estrategia" varchar(60) NOT NULL,
    "pesos" jsonb NOT NULL,
    "versao_modelo" varchar(120) NOT NULL,
    "usou_rerank" boolean NOT NULL,
    "fallback_usado" boolean NOT NULL,
    "executado_por" varchar(160) NOT NULL,
    "status" varchar(12) NOT NULL,
    "erro" text NOT NULL,
    "id_execucao_ia" uuid NULL,
    "iniciado_em" timestamp with time zone NOT NULL,
    "concluido_em" timestamp with time zone NULL
);

-- ---------------------------------------------------------------------------
-- maturity - Pre-analise de maturidade
-- ---------------------------------------------------------------------------

CREATE TABLE "criterio_pre_analise" (
    "id_criterio" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "versao" varchar(12) NOT NULL,
    "dimensao" varchar(24) NOT NULL,
    "codigo" varchar(40) NOT NULL,
    "descricao" text NOT NULL,
    "peso" numeric(5, 2) NULL,
    "vigente_de" date NOT NULL,
    "vigente_ate" date NULL,
    CONSTRAINT "uq_criterio_versao_codigo" UNIQUE ("versao", "codigo")
);

CREATE TABLE "pre_analise" (
    "id_pre_analise" uuid NOT NULL PRIMARY KEY,
    "id_oportunidade" bigint NOT NULL,
    "versao_criterios" varchar(12) NOT NULL,
    "versao_proposta" integer NOT NULL CHECK ("versao_proposta" >= 0),
    "sintese" text NOT NULL,
    "executada_em" timestamp with time zone NOT NULL,
    "executada_por" varchar(160) NOT NULL,
    "id_execucao_ia" uuid NULL,
    "status" varchar(12) NOT NULL,
    "erro" text NOT NULL
);

CREATE TABLE "pre_analise_dimensao" (
    "id_dimensao" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "id_pre_analise" uuid NOT NULL,
    "dimensao" varchar(24) NOT NULL,
    "avaliacao" text NOT NULL,
    "nivel" varchar(20) NOT NULL,
    "evidencias" jsonb NOT NULL,
    "ordem" smallint NOT NULL CHECK ("ordem" >= 0),
    CONSTRAINT "uq_pre_analise_dimensao" UNIQUE ("id_pre_analise", "dimensao")
);

CREATE TABLE "recomendacao" (
    "id_recomendacao" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "id_oportunidade" bigint NOT NULL,
    "origem" varchar(12) NOT NULL,
    "id_pre_analise" uuid NULL,
    "id_lacuna" bigint NULL,
    "texto" text NOT NULL,
    "acatada" boolean NOT NULL,
    "acatada_em" timestamp with time zone NULL,
    "id_execucao_ia" uuid NULL,
    "criado_em" timestamp with time zone NOT NULL
);

-- ---------------------------------------------------------------------------
-- decisions - Decisao do Supervisor
-- ---------------------------------------------------------------------------

CREATE TABLE "decisao" (
    "id_decisao" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "id_oportunidade" bigint NOT NULL,
    "tipo" varchar(10) NOT NULL,
    "justificativa" text NOT NULL,
    "id_autor" bigint NOT NULL,
    "id_pre_analise" uuid NULL,
    "registrada_em" timestamp with time zone NOT NULL
);

-- ---------------------------------------------------------------------------
-- audit - Trilha de auditoria
-- ---------------------------------------------------------------------------

CREATE TABLE "evento_auditoria" (
    "id_evento" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "ocorrido_em" timestamp with time zone NOT NULL,
    "categoria" varchar(16) NOT NULL,
    "tipo" varchar(60) NOT NULL,
    "ator" varchar(160) NOT NULL,
    "entidade" varchar(60) NOT NULL,
    "entidade_id" varchar(60) NOT NULL,
    "status" varchar(8) NOT NULL,
    "motivo" text NOT NULL,
    "correlation_id" uuid NOT NULL,
    "id_execucao_ia" uuid NULL,
    "detalhe" jsonb NOT NULL,
    "registrado_em" timestamp with time zone NOT NULL
);

-- ---------------------------------------------------------------------------
-- notifications - Notificacoes
-- ---------------------------------------------------------------------------

CREATE TABLE "notificacao" (
    "id_notificacao" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "id_usuario" bigint NOT NULL,
    "tipo" varchar(60) NOT NULL,
    "titulo" varchar(200) NOT NULL,
    "mensagem" text NOT NULL,
    "entidade" varchar(60) NOT NULL,
    "entidade_id" varchar(60) NOT NULL,
    "lida_em" timestamp with time zone NULL,
    "criado_em" timestamp with time zone NOT NULL
);

-- ---------------------------------------------------------------------------
-- admin - Django - log do admin
-- ---------------------------------------------------------------------------

CREATE TABLE "django_admin_log" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "action_time" timestamp with time zone NOT NULL,
    "user_id" bigint NOT NULL,
    "content_type_id" integer NULL,
    "object_id" text NULL,
    "object_repr" varchar(200) NOT NULL,
    "action_flag" smallint NOT NULL CHECK ("action_flag" >= 0),
    "change_message" text NOT NULL
);

-- ---------------------------------------------------------------------------
-- auth - Django - permissoes e grupos
-- ---------------------------------------------------------------------------

CREATE TABLE "auth_group" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(150) NOT NULL UNIQUE
);

CREATE TABLE "auth_group_permissions" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "group_id" integer NOT NULL,
    "permission_id" integer NOT NULL
);

CREATE TABLE "auth_permission" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(255) NOT NULL,
    "content_type_id" integer NOT NULL,
    "codename" varchar(100) NOT NULL
);

-- ---------------------------------------------------------------------------
-- contenttypes - Django - tipos de conteudo
-- ---------------------------------------------------------------------------

CREATE TABLE "django_content_type" (
    "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "app_label" varchar(100) NOT NULL,
    "model" varchar(100) NOT NULL
);

-- ---------------------------------------------------------------------------
-- sessions - Django - sessoes
-- ---------------------------------------------------------------------------

CREATE TABLE "django_session" (
    "session_key" varchar(40) NOT NULL PRIMARY KEY,
    "session_data" text NOT NULL,
    "expire_date" timestamp with time zone NOT NULL
);

-- ---------------------------------------------------------------------------
-- token_blacklist - SimpleJWT - refresh tokens e blacklist
-- ---------------------------------------------------------------------------

CREATE TABLE "token_blacklist_blacklistedtoken" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "token_id" bigint NOT NULL UNIQUE,
    "blacklisted_at" timestamp with time zone NOT NULL
);

CREATE TABLE "token_blacklist_outstandingtoken" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NULL,
    "jti" varchar(255) NOT NULL,
    "token" text NOT NULL,
    "created_at" timestamp with time zone NULL,
    "expires_at" timestamp with time zone NOT NULL
);


-- ############################  2. INDICES  ############################


-- anexo_oportunidade
CREATE INDEX "anexo_oportunidade_enviado_por_fc238849" ON "anexo_oportunidade" ("enviado_por");
CREATE INDEX "anexo_oportunidade_id_oportunidade_2549eb8b" ON "anexo_oportunidade" ("id_oportunidade");

-- auth_group
CREATE INDEX "auth_group_name_a6ea08ec_like" ON "auth_group" ("name" varchar_pattern_ops);

-- auth_group_permissions
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");

-- auth_permission
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");

-- competencia
CREATE INDEX "competencia_id_sinonimo_de_5488948b" ON "competencia" ("id_sinonimo_de");

-- competencia_necessaria
CREATE INDEX "competencia_necessaria_id_competencia_f0d5e595" ON "competencia_necessaria" ("id_competencia");
CREATE INDEX "competencia_necessaria_id_execucao_ia_560c0772" ON "competencia_necessaria" ("id_execucao_ia");
CREATE INDEX "competencia_necessaria_id_oportunidade_850c09b0" ON "competencia_necessaria" ("id_oportunidade");

-- configuracao_plataforma
CREATE INDEX "configuracao_plataforma_atualizado_por_7c5a06e2" ON "configuracao_plataforma" ("atualizado_por");
CREATE INDEX "configuracao_plataforma_secao_37efeaa0_like" ON "configuracao_plataforma" ("secao" varchar_pattern_ops);

-- decisao
CREATE INDEX "decisao_id_autor_afad7afe" ON "decisao" ("id_autor");
CREATE INDEX "decisao_id_oportunidade_6344137c" ON "decisao" ("id_oportunidade");
CREATE INDEX "decisao_id_pre_analise_b439f378" ON "decisao" ("id_pre_analise");
CREATE INDEX "idx_decisao_oportunidade" ON "decisao" ("id_oportunidade", "registrada_em" DESC);

-- django_admin_log
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");

-- django_session
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE INDEX "django_session_session_key_c0390e0f_like" ON "django_session" ("session_key" varchar_pattern_ops);

-- equipe_potencial
CREATE INDEX "equipe_potencial_ajustado_por_a505a168" ON "equipe_potencial" ("ajustado_por");
CREATE INDEX "equipe_potencial_id_execucao_f94799e7" ON "equipe_potencial" ("id_execucao");
CREATE INDEX "equipe_potencial_id_membro_1163f330" ON "equipe_potencial" ("id_membro");
CREATE INDEX "equipe_potencial_id_oportunidade_a0017d91" ON "equipe_potencial" ("id_oportunidade");
CREATE INDEX "idx_equipe_membro_validada" ON "equipe_potencial" ("id_membro", "validada");

-- evento_auditoria
CREATE INDEX "evento_auditoria_id_execucao_ia_9bb2739f" ON "evento_auditoria" ("id_execucao_ia");
CREATE INDEX "idx_evento_categoria" ON "evento_auditoria" ("categoria", "ocorrido_em" DESC);
CREATE INDEX "idx_evento_correlation" ON "evento_auditoria" ("correlation_id");
CREATE INDEX "idx_evento_entidade" ON "evento_auditoria" ("entidade", "entidade_id", "ocorrido_em" DESC);

-- execucao_ia
CREATE INDEX "idx_execia_consumo_ok" ON "execucao_ia" ("criado_em") WHERE "status" = 'ok';
CREATE INDEX "idx_execia_correlation" ON "execucao_ia" ("correlation_id");

-- execucao_matching
CREATE INDEX "execucao_matching_id_execucao_ia_3f58ab1f" ON "execucao_matching" ("id_execucao_ia");
CREATE INDEX "execucao_matching_id_oportunidade_4bb32fc8" ON "execucao_matching" ("id_oportunidade");

-- formacao
CREATE INDEX "formacao_id_membro_cbf325f1" ON "formacao" ("id_membro");
CREATE INDEX "formacao_id_titulacao_e181dd1c" ON "formacao" ("id_titulacao");

-- lacuna
CREATE INDEX "idx_lacuna_oport_tipo" ON "lacuna" ("id_oportunidade", "tipo", "resolvida");
CREATE INDEX "lacuna_id_competencia_necessaria_2aaded00" ON "lacuna" ("id_competencia_necessaria");
CREATE INDEX "lacuna_id_execucao_ia_c741fe95" ON "lacuna" ("id_execucao_ia");
CREATE INDEX "lacuna_id_oportunidade_468581cc" ON "lacuna" ("id_oportunidade");
CREATE INDEX "lacuna_id_pre_analise_f1d021e0" ON "lacuna" ("id_pre_analise");

-- membro_competencia
CREATE INDEX "membro_competencia_id_competencia_e9f66c9a" ON "membro_competencia" ("id_competencia");
CREATE INDEX "membro_competencia_id_membro_2f7a5b13" ON "membro_competencia" ("id_membro");

-- membro_rede
CREATE INDEX "idx_membro_situacao_disp" ON "membro_rede" ("situacao", "disponibilidade");
CREATE INDEX "membro_rede_cadastrado_por_191f948a" ON "membro_rede" ("cadastrado_por");
CREATE INDEX "membro_rede_email_1f8927f8_like" ON "membro_rede" ("email" varchar_pattern_ops);
CREATE INDEX "membro_rede_id_organizacao_77ec2204" ON "membro_rede" ("id_organizacao");
CREATE INDEX "membro_rede_id_titulacao_6f7d6db1" ON "membro_rede" ("id_titulacao");

-- mensagem_copiloto
CREATE INDEX "mensagem_copiloto_id_execucao_ia_79dbebab" ON "mensagem_copiloto" ("id_execucao_ia");
CREATE INDEX "mensagem_copiloto_id_sessao_4af14a21" ON "mensagem_copiloto" ("id_sessao");

-- notificacao
CREATE INDEX "idx_notif_usuario_lida" ON "notificacao" ("id_usuario", "lida_em");
CREATE INDEX "notificacao_id_usuario_11de9145" ON "notificacao" ("id_usuario");

-- oportunidade
CREATE INDEX "idx_oport_fila_supervisor" ON "oportunidade" ("situacao", "atualizada_em" DESC);
CREATE INDEX "oportunidade_codigo_d8782bdd_like" ON "oportunidade" ("codigo" varchar_pattern_ops);
CREATE INDEX "oportunidade_id_criado_por_1e0b324b" ON "oportunidade" ("id_criado_por");
CREATE INDEX "oportunidade_id_demandante_7ab18b3e" ON "oportunidade" ("id_demandante");
CREATE INDEX "oportunidade_id_responsavel_17065724" ON "oportunidade" ("id_responsavel");

-- organizacao
CREATE INDEX "organizacao_cnpj_8b074ee9_like" ON "organizacao" ("cnpj" varchar_pattern_ops);

-- pre_analise
CREATE INDEX "pre_analise_id_execucao_ia_8b910329" ON "pre_analise" ("id_execucao_ia");
CREATE INDEX "pre_analise_id_oportunidade_04dcbf81" ON "pre_analise" ("id_oportunidade");

-- pre_analise_dimensao
CREATE INDEX "pre_analise_dimensao_id_pre_analise_e640edf2" ON "pre_analise_dimensao" ("id_pre_analise");

-- proposta_estruturada
CREATE INDEX "proposta_estruturada_id_execucao_ia_2176e324" ON "proposta_estruturada" ("id_execucao_ia");
CREATE INDEX "proposta_estruturada_id_revisor_bf8c78be" ON "proposta_estruturada" ("id_revisor");

-- recomendacao
CREATE INDEX "recomendacao_id_execucao_ia_daecd88a" ON "recomendacao" ("id_execucao_ia");
CREATE INDEX "recomendacao_id_lacuna_467d3db6" ON "recomendacao" ("id_lacuna");
CREATE INDEX "recomendacao_id_oportunidade_f024c402" ON "recomendacao" ("id_oportunidade");
CREATE INDEX "recomendacao_id_pre_analise_e106d50b" ON "recomendacao" ("id_pre_analise");

-- sessao_copiloto
CREATE INDEX "sessao_copiloto_id_oportunidade_510620f7" ON "sessao_copiloto" ("id_oportunidade");
CREATE INDEX "sessao_copiloto_iniciada_por_9ce7870d" ON "sessao_copiloto" ("iniciada_por");

-- titulacao
CREATE INDEX "titulacao_codigo_57fc717b_like" ON "titulacao" ("codigo" varchar_pattern_ops);

-- token_acesso
CREATE INDEX "idx_token_usuario_final" ON "token_acesso" ("id_usuario", "finalidade");
CREATE INDEX "token_acesso_id_usuario_a1aa4e80" ON "token_acesso" ("id_usuario");
CREATE INDEX "token_acesso_token_8f32a840_like" ON "token_acesso" ("token" varchar_pattern_ops);

-- token_blacklist_outstandingtoken
CREATE INDEX "token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like" ON "token_blacklist_outstandingtoken" ("jti" varchar_pattern_ops);
CREATE INDEX "token_blacklist_outstandingtoken_user_id_83bc629a" ON "token_blacklist_outstandingtoken" ("user_id");

-- usuario
CREATE INDEX "idx_usuario_papel_situacao" ON "usuario" ("papel", "situacao");
CREATE INDEX "usuario_email_de9343f9_like" ON "usuario" ("email" varchar_pattern_ops);
CREATE INDEX "usuario_id_organizacao_5418ae0f" ON "usuario" ("id_organizacao");

-- usuario_groups
CREATE INDEX "usuario_groups_group_id_c67c8651" ON "usuario_groups" ("group_id");
CREATE INDEX "usuario_groups_usuario_id_161fc80c" ON "usuario_groups" ("usuario_id");

-- usuario_user_permissions
CREATE INDEX "usuario_user_permissions_permission_id_a8893ce7" ON "usuario_user_permissions" ("permission_id");
CREATE INDEX "usuario_user_permissions_usuario_id_693d9c50" ON "usuario_user_permissions" ("usuario_id");


-- ##########  3. CHAVES ESTRANGEIRAS E CONSTRAINTS UNIQUE  ##########


-- anexo_oportunidade
ALTER TABLE "anexo_oportunidade" ADD CONSTRAINT "anexo_oportunidade_enviado_por_fc238849_fk_usuario_id_usuario" FOREIGN KEY ("enviado_por") REFERENCES "usuario" ("id_usuario") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "anexo_oportunidade" ADD CONSTRAINT "anexo_oportunidade_id_oportunidade_2549eb8b_fk_oportunid" FOREIGN KEY ("id_oportunidade") REFERENCES "oportunidade" ("id_oportunidade") DEFERRABLE INITIALLY DEFERRED;

-- auth_group_permissions
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE ("group_id", "permission_id");

-- auth_permission
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE ("content_type_id", "codename");

-- competencia
ALTER TABLE "competencia" ADD CONSTRAINT "competencia_id_sinonimo_de_5488948b_fk_competenc" FOREIGN KEY ("id_sinonimo_de") REFERENCES "competencia" ("id_competencia") DEFERRABLE INITIALLY DEFERRED;

-- competencia_necessaria
ALTER TABLE "competencia_necessaria" ADD CONSTRAINT "competencia_necessar_id_competencia_f0d5e595_fk_competenc" FOREIGN KEY ("id_competencia") REFERENCES "competencia" ("id_competencia") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "competencia_necessaria" ADD CONSTRAINT "competencia_necessar_id_execucao_ia_560c0772_fk_execucao_" FOREIGN KEY ("id_execucao_ia") REFERENCES "execucao_ia" ("id_execucao_ia") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "competencia_necessaria" ADD CONSTRAINT "competencia_necessar_id_oportunidade_850c09b0_fk_oportunid" FOREIGN KEY ("id_oportunidade") REFERENCES "oportunidade" ("id_oportunidade") DEFERRABLE INITIALLY DEFERRED;

-- configuracao_plataforma
ALTER TABLE "configuracao_plataforma" ADD CONSTRAINT "configuracao_platafo_atualizado_por_7c5a06e2_fk_usuario_i" FOREIGN KEY ("atualizado_por") REFERENCES "usuario" ("id_usuario") DEFERRABLE INITIALLY DEFERRED;

-- decisao
ALTER TABLE "decisao" ADD CONSTRAINT "decisao_id_autor_afad7afe_fk_usuario_id_usuario" FOREIGN KEY ("id_autor") REFERENCES "usuario" ("id_usuario") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "decisao" ADD CONSTRAINT "decisao_id_oportunidade_6344137c_fk_oportunid" FOREIGN KEY ("id_oportunidade") REFERENCES "oportunidade" ("id_oportunidade") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "decisao" ADD CONSTRAINT "decisao_id_pre_analise_b439f378_fk_pre_analise_id_pre_analise" FOREIGN KEY ("id_pre_analise") REFERENCES "pre_analise" ("id_pre_analise") DEFERRABLE INITIALLY DEFERRED;

-- django_admin_log
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_usuario_id_usuario" FOREIGN KEY ("user_id") REFERENCES "usuario" ("id_usuario") DEFERRABLE INITIALLY DEFERRED;

-- django_content_type
ALTER TABLE "django_content_type" ADD CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE ("app_label", "model");

-- equipe_potencial
ALTER TABLE "equipe_potencial" ADD CONSTRAINT "equipe_potencial_ajustado_por_a505a168_fk_usuario_id_usuario" FOREIGN KEY ("ajustado_por") REFERENCES "usuario" ("id_usuario") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "equipe_potencial" ADD CONSTRAINT "equipe_potencial_id_execucao_f94799e7_fk_execucao_" FOREIGN KEY ("id_execucao") REFERENCES "execucao_matching" ("id_execucao") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "equipe_potencial" ADD CONSTRAINT "equipe_potencial_id_membro_1163f330_fk_membro_rede_id_membro" FOREIGN KEY ("id_membro") REFERENCES "membro_rede" ("id_membro") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "equipe_potencial" ADD CONSTRAINT "equipe_potencial_id_oportunidade_a0017d91_fk_oportunid" FOREIGN KEY ("id_oportunidade") REFERENCES "oportunidade" ("id_oportunidade") DEFERRABLE INITIALLY DEFERRED;

-- evento_auditoria
ALTER TABLE "evento_auditoria" ADD CONSTRAINT "evento_auditoria_id_execucao_ia_9bb2739f_fk_execucao_" FOREIGN KEY ("id_execucao_ia") REFERENCES "execucao_ia" ("id_execucao_ia") DEFERRABLE INITIALLY DEFERRED;

-- execucao_matching
ALTER TABLE "execucao_matching" ADD CONSTRAINT "execucao_matching_id_execucao_ia_3f58ab1f_fk_execucao_" FOREIGN KEY ("id_execucao_ia") REFERENCES "execucao_ia" ("id_execucao_ia") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "execucao_matching" ADD CONSTRAINT "execucao_matching_id_oportunidade_4bb32fc8_fk_oportunid" FOREIGN KEY ("id_oportunidade") REFERENCES "oportunidade" ("id_oportunidade") DEFERRABLE INITIALLY DEFERRED;

-- formacao
ALTER TABLE "formacao" ADD CONSTRAINT "formacao_id_membro_cbf325f1_fk_membro_rede_id_membro" FOREIGN KEY ("id_membro") REFERENCES "membro_rede" ("id_membro") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "formacao" ADD CONSTRAINT "formacao_id_titulacao_e181dd1c_fk_titulacao_id_titulacao" FOREIGN KEY ("id_titulacao") REFERENCES "titulacao" ("id_titulacao") DEFERRABLE INITIALLY DEFERRED;

-- lacuna
ALTER TABLE "lacuna" ADD CONSTRAINT "lacuna_id_competencia_neces_2aaded00_fk_competenc" FOREIGN KEY ("id_competencia_necessaria") REFERENCES "competencia_necessaria" ("id_competencia_necessaria") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "lacuna" ADD CONSTRAINT "lacuna_id_execucao_ia_c741fe95_fk_execucao_ia_id_execucao_ia" FOREIGN KEY ("id_execucao_ia") REFERENCES "execucao_ia" ("id_execucao_ia") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "lacuna" ADD CONSTRAINT "lacuna_id_oportunidade_468581cc_fk_oportunidade_id_oportunidade" FOREIGN KEY ("id_oportunidade") REFERENCES "oportunidade" ("id_oportunidade") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "lacuna" ADD CONSTRAINT "lacuna_id_pre_analise_f1d021e0_fk_pre_analise_id_pre_analise" FOREIGN KEY ("id_pre_analise") REFERENCES "pre_analise" ("id_pre_analise") DEFERRABLE INITIALLY DEFERRED;

-- membro_competencia
ALTER TABLE "membro_competencia" ADD CONSTRAINT "membro_competencia_id_competencia_e9f66c9a_fk_competenc" FOREIGN KEY ("id_competencia") REFERENCES "competencia" ("id_competencia") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "membro_competencia" ADD CONSTRAINT "membro_competencia_id_membro_2f7a5b13_fk_membro_rede_id_membro" FOREIGN KEY ("id_membro") REFERENCES "membro_rede" ("id_membro") DEFERRABLE INITIALLY DEFERRED;

-- membro_rede
ALTER TABLE "membro_rede" ADD CONSTRAINT "membro_rede_cadastrado_por_191f948a_fk_usuario_id_usuario" FOREIGN KEY ("cadastrado_por") REFERENCES "usuario" ("id_usuario") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "membro_rede" ADD CONSTRAINT "membro_rede_id_organizacao_77ec2204_fk_organizac" FOREIGN KEY ("id_organizacao") REFERENCES "organizacao" ("id_organizacao") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "membro_rede" ADD CONSTRAINT "membro_rede_id_titulacao_6f7d6db1_fk_titulacao_id_titulacao" FOREIGN KEY ("id_titulacao") REFERENCES "titulacao" ("id_titulacao") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "membro_rede" ADD CONSTRAINT "membro_rede_id_usuario_ba6f603f_fk_usuario_id_usuario" FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario") DEFERRABLE INITIALLY DEFERRED;

-- mensagem_copiloto
ALTER TABLE "mensagem_copiloto" ADD CONSTRAINT "mensagem_copiloto_id_execucao_ia_79dbebab_fk_execucao_" FOREIGN KEY ("id_execucao_ia") REFERENCES "execucao_ia" ("id_execucao_ia") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mensagem_copiloto" ADD CONSTRAINT "mensagem_copiloto_id_sessao_4af14a21_fk_sessao_co" FOREIGN KEY ("id_sessao") REFERENCES "sessao_copiloto" ("id_sessao") DEFERRABLE INITIALLY DEFERRED;

-- notificacao
ALTER TABLE "notificacao" ADD CONSTRAINT "notificacao_id_usuario_11de9145_fk_usuario_id_usuario" FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario") DEFERRABLE INITIALLY DEFERRED;

-- oportunidade
ALTER TABLE "oportunidade" ADD CONSTRAINT "oportunidade_id_criado_por_1e0b324b_fk_usuario_id_usuario" FOREIGN KEY ("id_criado_por") REFERENCES "usuario" ("id_usuario") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "oportunidade" ADD CONSTRAINT "oportunidade_id_demandante_7ab18b3e_fk_organizac" FOREIGN KEY ("id_demandante") REFERENCES "organizacao" ("id_organizacao") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "oportunidade" ADD CONSTRAINT "oportunidade_id_responsavel_17065724_fk_membro_rede_id_membro" FOREIGN KEY ("id_responsavel") REFERENCES "membro_rede" ("id_membro") DEFERRABLE INITIALLY DEFERRED;

-- pre_analise
ALTER TABLE "pre_analise" ADD CONSTRAINT "pre_analise_id_execucao_ia_8b910329_fk_execucao_" FOREIGN KEY ("id_execucao_ia") REFERENCES "execucao_ia" ("id_execucao_ia") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "pre_analise" ADD CONSTRAINT "pre_analise_id_oportunidade_04dcbf81_fk_oportunid" FOREIGN KEY ("id_oportunidade") REFERENCES "oportunidade" ("id_oportunidade") DEFERRABLE INITIALLY DEFERRED;

-- pre_analise_dimensao
ALTER TABLE "pre_analise_dimensao" ADD CONSTRAINT "pre_analise_dimensao_id_pre_analise_e640edf2_fk_pre_anali" FOREIGN KEY ("id_pre_analise") REFERENCES "pre_analise" ("id_pre_analise") DEFERRABLE INITIALLY DEFERRED;

-- proposta_estruturada
ALTER TABLE "proposta_estruturada" ADD CONSTRAINT "proposta_estruturada_id_execucao_ia_2176e324_fk_execucao_" FOREIGN KEY ("id_execucao_ia") REFERENCES "execucao_ia" ("id_execucao_ia") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "proposta_estruturada" ADD CONSTRAINT "proposta_estruturada_id_oportunidade_d0526950_fk_oportunid" FOREIGN KEY ("id_oportunidade") REFERENCES "oportunidade" ("id_oportunidade") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "proposta_estruturada" ADD CONSTRAINT "proposta_estruturada_id_revisor_bf8c78be_fk_usuario_id_usuario" FOREIGN KEY ("id_revisor") REFERENCES "usuario" ("id_usuario") DEFERRABLE INITIALLY DEFERRED;

-- recomendacao
ALTER TABLE "recomendacao" ADD CONSTRAINT "recomendacao_id_execucao_ia_daecd88a_fk_execucao_" FOREIGN KEY ("id_execucao_ia") REFERENCES "execucao_ia" ("id_execucao_ia") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "recomendacao" ADD CONSTRAINT "recomendacao_id_lacuna_467d3db6_fk_lacuna_id_lacuna" FOREIGN KEY ("id_lacuna") REFERENCES "lacuna" ("id_lacuna") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "recomendacao" ADD CONSTRAINT "recomendacao_id_oportunidade_f024c402_fk_oportunid" FOREIGN KEY ("id_oportunidade") REFERENCES "oportunidade" ("id_oportunidade") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "recomendacao" ADD CONSTRAINT "recomendacao_id_pre_analise_e106d50b_fk_pre_anali" FOREIGN KEY ("id_pre_analise") REFERENCES "pre_analise" ("id_pre_analise") DEFERRABLE INITIALLY DEFERRED;

-- sessao_copiloto
ALTER TABLE "sessao_copiloto" ADD CONSTRAINT "sessao_copiloto_id_oportunidade_510620f7_fk_oportunid" FOREIGN KEY ("id_oportunidade") REFERENCES "oportunidade" ("id_oportunidade") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sessao_copiloto" ADD CONSTRAINT "sessao_copiloto_iniciada_por_9ce7870d_fk_usuario_id_usuario" FOREIGN KEY ("iniciada_por") REFERENCES "usuario" ("id_usuario") DEFERRABLE INITIALLY DEFERRED;

-- token_acesso
ALTER TABLE "token_acesso" ADD CONSTRAINT "token_acesso_id_usuario_a1aa4e80_fk_usuario_id_usuario" FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario") DEFERRABLE INITIALLY DEFERRED;

-- token_blacklist_blacklistedtoken
ALTER TABLE "token_blacklist_blacklistedtoken" ADD CONSTRAINT "token_blacklist_blac_token_id_3cc7fe56_fk_token_bla" FOREIGN KEY ("token_id") REFERENCES "token_blacklist_outstandingtoken" ("id") DEFERRABLE INITIALLY DEFERRED;

-- token_blacklist_outstandingtoken
ALTER TABLE "token_blacklist_outstandingtoken" ADD CONSTRAINT "token_blacklist_outs_user_id_83bc629a_fk_usuario_i" FOREIGN KEY ("user_id") REFERENCES "usuario" ("id_usuario") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "token_blacklist_outstandingtoken" ADD CONSTRAINT "token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq" UNIQUE ("jti");

-- usuario
ALTER TABLE "usuario" ADD CONSTRAINT "usuario_id_organizacao_5418ae0f_fk_organizacao_id_organizacao" FOREIGN KEY ("id_organizacao") REFERENCES "organizacao" ("id_organizacao") DEFERRABLE INITIALLY DEFERRED;

-- usuario_groups
ALTER TABLE "usuario_groups" ADD CONSTRAINT "usuario_groups_group_id_c67c8651_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "usuario_groups" ADD CONSTRAINT "usuario_groups_usuario_id_161fc80c_fk_usuario_id_usuario" FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id_usuario") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "usuario_groups" ADD CONSTRAINT "usuario_groups_usuario_id_group_id_2e3cd638_uniq" UNIQUE ("usuario_id", "group_id");

-- usuario_user_permissions
ALTER TABLE "usuario_user_permissions" ADD CONSTRAINT "usuario_user_permiss_permission_id_a8893ce7_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "usuario_user_permissions" ADD CONSTRAINT "usuario_user_permiss_usuario_id_693d9c50_fk_usuario_i" FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id_usuario") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "usuario_user_permissions" ADD CONSTRAINT "usuario_user_permissions_usuario_id_permission_id_3db58b8c_uniq" UNIQUE ("usuario_id", "permission_id");

COMMIT;
