"""
O par da 0003: e aqui que o `RENAME COLUMN` acontece.

A 0003 renomeia o campo no estado do Django e sai como no-op no banco, porque
o `db_column` antigo ainda vale naquele ponto. Esta migration alinha o
`db_column` e o banco renomeia a coluna - sem dropar, sem perder linha.
"""
# Generated by Django 5.2.14 on 2026-09-25 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0003_nomes_do_diagrama'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisao',
            name='observacoes',
            field=models.TextField(db_column='observacoes'),
        ),
        migrations.AlterField(
            model_name='decisao',
            name='responsavel',
            field=models.ForeignKey(db_column='id_responsavel', on_delete=django.db.models.deletion.PROTECT, related_name='decisoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='decisao',
            name='tipo_decisao',
            field=models.CharField(choices=[('continuar', 'Continuar'), ('revisar', 'Revisar'), ('arquivar', 'Arquivar')], db_column='tipo_decisao', max_length=10),
        ),
    ]
