"""
Aplica as migrations do Django no Neon pelo endpoint HTTP (porta 443).

POR QUE ISTO EXISTE
-------------------
O `manage.py migrate` fala o protocolo nativo do Postgres na porta 5432. Em
redes que bloqueiam a 5432 de saida - o caso da maquina onde este backend
nasceu - a conexao morre em `timeout expired` e nao ha migrate possivel. O Neon
tambem responde SQL sobre HTTPS na 443, que passa. Este script usa esse
caminho.

O QUE ELE NAO E
---------------
Nao e um canal alternativo de schema. O SQL aplicado aqui e *gerado pelo
Django* a partir das migrations (`sqlmigrate`), nunca escrito a mao: a migration
continua sendo o canal unico (AGENTS.md 2.2). O script tambem grava a linha
correspondente em `django_migrations`, de modo que um `migrate` futuro, de uma
rede sem bloqueio, encontre o banco no estado certo e nao reaplique nada.

Assim que a 5432 estiver acessivel, use `manage.py migrate` e esqueca este
arquivo.

USO
---
    python scripts/neon_migrate.py --plano      # mostra o que falta aplicar
    python scripts/neon_migrate.py --aplicar    # aplica

As credenciais saem de NEON_DB_* no `backend/.env`.
"""
import argparse
import os
import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE_DIR))

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')

import django  # noqa: E402

django.setup()

import sqlparse  # noqa: E402
from django.conf import settings  # noqa: E402
from django.core.management import call_command  # noqa: E402
from django.db import connection  # noqa: E402
from django.db.migrations.loader import MigrationLoader  # noqa: E402

from scripts.neon_http import Neon  # noqa: E402

DDL_DJANGO_MIGRATIONS = """
CREATE TABLE IF NOT EXISTS "django_migrations" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "app" varchar(255) NOT NULL,
    "name" varchar(255) NOT NULL,
    "applied" timestamp with time zone NOT NULL
)
"""


class MigradorNeon(Neon):
    """O cliente HTTP mais o que o `migrate` precisa saber: o que ja foi aplicado."""

    def aplicadas(self):
        self.executar(DDL_DJANGO_MIGRATIONS)
        return {(app, nome) for app, nome in self.linhas(
            'SELECT app, name FROM django_migrations'
        )}

    def registrar(self, app, nome):
        self.executar(
            'INSERT INTO django_migrations (app, name, applied) '
            'VALUES ($1, $2, now())',
            [app, nome],
        )


def ordem_de_aplicacao():
    """
    A ordem em que o Django aplicaria as migrations num banco vazio.

    Sai do proprio grafo do Django - nao de uma lista escrita a mao.
    """
    loader = MigrationLoader(connection, ignore_no_migrations=True)
    ordenadas = []

    for no in loader.graph.leaf_nodes():
        for dependencia in loader.graph.forwards_plan(no):
            if dependencia not in ordenadas:
                ordenadas.append(dependencia)

    return ordenadas


def sql_da_migration(app, name):
    """Pergunta ao Django qual DDL esta migration emite. Nada e escrito a mao."""
    from io import StringIO

    saida = StringIO()
    call_command('sqlmigrate', app, name, stdout=saida, no_color=True)
    return saida.getvalue()


def instrucoes(sql_bruto):
    """
    Quebra o script em instrucoes executaveis.

    O `sqlmigrate` prefixa cada comando com um bloco de comentario ("-- Create
    model X"). O `sqlparse.split` mantem esse comentario grudado na instrucao
    seguinte, entao descartar o pedaco inteiro por comecar com `--` engoliria o
    CREATE TABLE junto. Aqui os comentarios de cabecalho sao removidos linha a
    linha e o que sobra e que decide se ha comando ou nao.
    """
    resultado = []

    for pedaco in sqlparse.split(sql_bruto):
        linhas = [
            linha
            for linha in pedaco.splitlines()
            if linha.strip() and not linha.strip().startswith('--')
        ]
        limpa = '\n'.join(linhas).strip().rstrip(';').strip()

        if not limpa:
            continue
        if limpa.upper() in {'BEGIN', 'COMMIT'}:
            continue

        resultado.append(limpa)

    return resultado


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--aplicar', action='store_true', help='aplica as migrations')
    parser.add_argument('--plano', action='store_true', help='so mostra o que falta')
    args = parser.parse_args()

    if settings.RUNNING_TESTS:
        raise SystemExit('Este script nunca roda durante a suite de testes.')

    if not args.aplicar and not args.plano:
        parser.error('escolha --plano ou --aplicar')

    neon = MigradorNeon()
    print(f'Neon: {neon.dbname} @ {neon.host}')

    ja_aplicadas = neon.aplicadas()
    pendentes = [no for no in ordem_de_aplicacao() if no not in ja_aplicadas]

    print(f'{len(ja_aplicadas)} migration(s) ja aplicada(s); {len(pendentes)} pendente(s).')

    if not pendentes:
        print('Nada a fazer.')
        return

    for app, name in pendentes:
        print(f'  - {app}.{name}')

    if args.plano:
        return

    for app, name in pendentes:
        sql = sql_da_migration(app, name)
        comandos = instrucoes(sql)
        print(f'Aplicando {app}.{name} ({len(comandos)} instrucao/oes)...', end=' ')

        for comando in comandos:
            neon.executar(comando)

        neon.registrar(app, name)
        print('OK')

    print('Concluido.')


if __name__ == '__main__':
    main()
