# Generated by Django 5.2.14 on 2026-09-25 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_eventoauditoria_table'),
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoauditoria',
            name='oportunidade',
            field=models.ForeignKey(blank=True, db_column='id_oportunidade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='opportunities.oportunidade'),
        ),
    ]
