# Generated by Django 5.2.14 on 2026-09-24 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maturity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='criteriopreanalise',
            table='criterio_referencia_pipe',
        ),
        migrations.AlterModelTable(
            name='preanalise',
            table='pre_analise_maturidade',
        ),
        migrations.AlterModelTable(
            name='preanalisedimensao',
            table='dimensao_analise',
        ),
        migrations.AlterModelTable(
            name='recomendacao',
            table='recomendacao_adequacao',
        ),
    ]
