# Generated by Django 5.2.14 on 2026-09-24 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandanteExterno',
            fields=[
                ('usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_demandante', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telefone', models.CharField(blank=True, db_column='telefone', default='', max_length=20)),
            ],
            options={
                'verbose_name': 'demandante externo',
                'verbose_name_plural': 'demandantes externos',
                'db_table': 'demandante_externo',
            },
        ),
    ]
