# Generated by Django 5.2.14 on 2026-09-24 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='membrocompetencia',
            table='competencia_perfil',
        ),
    ]
