# Generated by Django 5.2.14 on 2026-09-24 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copilot', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lacuna',
            table='lacuna_proposta',
        ),
    ]
