# Generated by Django 5.2.14 on 2026-09-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copilot', '0004_remove_lacuna_competencia_necessaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lacuna',
            name='campo_afetado',
            field=models.CharField(blank=True, db_column='campo_afetado', default='', max_length=120),
        ),
        migrations.AddField(
            model_name='lacuna',
            name='recomendacao',
            field=models.TextField(blank=True, db_column='recomendacao', default=''),
        ),
    ]
