import { createElement } from 'react'
import {
  ArrowDown,
  ArrowLeft,
  ArrowUp,
  ArrowUpDown,
  Building2,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  CircleCheck,
  CircleMinus,
  Compass,
  Copy,
  Download,
  EllipsisVertical,
  Eye,
  EyeOff,
  Filter,
  FlaskConical,
  FolderOpen,
  History,
  Info,
  Lock,
  LogOut,
  Moon,
  Palette,
  Pencil,
  RotateCcw,
  Save,
  Scale,
  Search,
  Settings,
  Sun,
  Trash2,
  TriangleAlert,
  User,
  UserCog,
  UserPlus,
  Users,
  Workflow,
  X,
} from 'lucide-react'

export const appIcons = {
  themeDark: Moon,
  themeLight: Sun,
  passwordShow: Eye,
  passwordHide: EyeOff,
  warning: TriangleAlert,

  appearance: Palette,
  users: Users,
  search: Search,
  reset: RotateCcw,
  copy: Copy,
  done: Check,
  save: Save,
  disclosure: ChevronDown,
  profile: User,
  settings: Settings,
  logout: LogOut,

  addUser: UserPlus,
  export: Download,
  filter: Filter,
  info: Info,
  clear: X,
  more: EllipsisVertical,
  view: Eye,
  edit: Pencil,
  role: UserCog,
  activate: CircleCheck,
  deactivate: CircleMinus,
  remove: Trash2,
  researcher: FlaskConical,
  demo: FlaskConical,
  company: Building2,
  active: CircleCheck,

  folder: FolderOpen,
  flow: Workflow,
  decision: Scale,
  history: History,
  lock: Lock,
  back: ArrowLeft,
  compass: Compass,

  sort: ArrowUpDown,
  sortAsc: ArrowUp,
  sortDesc: ArrowDown,
  first: ChevronsLeft,
  previous: ChevronLeft,
  next: ChevronRight,
  last: ChevronsRight,
}

export function Icone({ icon: Glifo, size = '1em', ...resto }) {
  if (!Glifo) return null

  return createElement(Glifo, { size, 'aria-hidden': 'true', ...resto })
}
