import {
  faAnglesLeft,
  faArrowLeft,
  faClockRotateLeft,
  faCompass,
  faFolderOpen,
  faLock,
  faScaleBalanced,
  faDiagramProject,
  faAnglesRight,
  faArrowRightFromBracket,
  faBuilding,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCircleCheck,
  faCircleInfo,
  faCircleMinus,
  faCopy,
  faDownload,
  faEllipsisVertical,
  faEye,
  faEyeSlash,
  faFilter,
  faFlask,
  faGear,
  faMagnifyingGlass,
  faMoon,
  faPalette,
  faPen,
  faRotateLeft,
  faSort,
  faSortDown,
  faSortUp,
  faSun,
  faTrash,
  faTriangleExclamation,
  faUser,
  faUserGear,
  faUserPlus,
  faUsers,
  faXmark,
} from '@fortawesome/free-solid-svg-icons'

export const appIcons = {
  themeDark: faMoon,
  themeLight: faSun,
  passwordShow: faEye,
  passwordHide: faEyeSlash,
  warning: faTriangleExclamation,

  // Console de administracao
  appearance: faPalette,
  users: faUsers,
  search: faMagnifyingGlass,
  reset: faRotateLeft,
  copy: faCopy,
  done: faCheck,
  disclosure: faChevronDown,
  profile: faUser,
  settings: faGear,
  logout: faArrowRightFromBracket,

  // Usuarios
  addUser: faUserPlus,
  export: faDownload,
  filter: faFilter,
  info: faCircleInfo,
  clear: faXmark,
  more: faEllipsisVertical,
  view: faEye,
  edit: faPen,
  role: faUserGear,
  activate: faCircleCheck,
  deactivate: faCircleMinus,
  remove: faTrash,
  researcher: faFlask,
  demo: faFlask,
  company: faBuilding,
  active: faCircleCheck,

  // Oportunidades e estados de rota
  folder: faFolderOpen,
  flow: faDiagramProject,
  decision: faScaleBalanced,
  history: faClockRotateLeft,
  lock: faLock,
  back: faArrowLeft,
  compass: faCompass,

  // Ordenacao e paginacao
  sort: faSort,
  sortAsc: faSortUp,
  sortDesc: faSortDown,
  first: faAnglesLeft,
  previous: faChevronLeft,
  next: faChevronRight,
  last: faAnglesRight,
}
